WishList/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.wishlist.urls', namespace="wishlist"))
]

apps/wishlist/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^main$', views.index, name="index"),
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.login, name="login"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^dashboard$', views.dashboard, name="dashboard"),
    url(r'^add$', views.add, name="additem"),
    url(r'^wish_items/create$', views.create, name="createitem"),
    url(r'^wish_items/(?P<id>\d+)$', views.show, name="show"),
    url(r'^wish_items/(?P<id>\d+)/delete$', views.delete, name="delete"),
    url(r'^remove/(?P<id>\d+)$', views.remove, name="remove"),
    url(r'^join/(?P<id>\d+)$', views.join, name="join")
]

apps/wishlist/models.py
from django.db import models
import bcrypt

class UserManager(models.Manager):
    def validate_user(self, form):
        errors = []

        if len(form['name']) < 3:
            errors.append("Name must be at least 3 characters long")
        if len(form['username']) < 3:
            errors.append("Username must be at least 3 characters long")
        if len(form['password']) < 8:
            errors.append("Password must be at least 8 characters long")        
        if form['password'] != form['confirm_pw']:
            errors.append("Passwords do not match")

        try:
            self.get(username=form['username'])
            errors.append("Username is already in use")
        except:
            pass

        return errors

    def create_user(self, user_data):
        pw_hash = bcrypt.hashpw(user_data['password'].encode(), bcrypt.gensalt())
        user = self.create(
            name=user_data['name'],
            username=user_data['username'],
            pw_hash=pw_hash,
            date_hired=user_data['date_hired']
        )
        return user
    
    def login(self, form):
        try:
            user = self.get(username=form['username'])
            if bcrypt.checkpw(form['password'].encode(), user.pw_hash.encode()):
                return(True, user.id)
            else:
                return(False, "Invalid username/password combination")
        except:
            return(False, "Account does not exist")

class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    pw_hash = models.CharField(max_length=255)
    date_hired = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

class ItemManager(models.Manager):
    def validate_item(self, form):
        errors = []
        if form['name'] == "":
            errors.append("Please enter an item")
        return errors

    def create_item(self, user_data, id):
        self.create(name=user_data['name'], user=User.objects.get(id=id))
    def join(self, item_id, user_id):
        self.get(id=item_id).join.add(user_id)
    def delete(self, item_id, user_id):
        self.get(id=item_id).join.remove(user_id)
    
class Item(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    join = models.ManyToManyField(User, related_name="Users")
    user = models.ForeignKey(User, related_name="items")
    objects = ItemManager()

apps/wishlist/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from .models import User, Item

def index(request):
    if 'id' in request.session:
        return redirect('/dashboard')
    return render(request, 'wishlist/index.html')

def register(request):
    if request.method != 'POST':
        return redirect('/')

    errors = User.objects.validate_user(request.POST)
    if len(errors) > 0:
        for error in errors:
            messages.error(request, error)
        return redirect('/')
    else:
        user = User.objects.create_user(request.POST)
        request.session['id'] = user.id
        return redirect('/dashboard')

def login(request):
    if request.method != 'POST':
        return redirect('/')

    valid, response = User.objects.login(request.POST)
    if valid == True:
        request.session['id'] = response
        return redirect('/dashboard')
    else:
        messages.error(request, response)
        return redirect('/')

def logout(request):
    request.session.clear()
    return redirect('/')

def dashboard(request):
    if 'id' not in request.session:
        return redirect('/')

    context = {
        'user': User.objects.get(id=request.session['id']),
        'myitems': Item.objects.filter(user=User.objects.get(id=request.session['id'])),
        'added': Item.objects.filter(join=User.objects.filter(id=request.session['id'])),
        'allitems': Item.objects.exclude(user=User.objects.get(id=request.session['id'])).exclude(join=User.objects.filter(id=request.session['id']))
    }
    return render(request, 'wishlist/dashboard.html', context)

def add(request):
    if 'id' not in request.session:
        return redirect('/')
    return render(request, 'wishlist/create_item.html')

def create(request):
    if 'id' not in request.session:
        return redirect('/')

    errors = Item.objects.validate_item(request.POST)
    if len(errors) > 0:
        for error in errors:
            messages.error(request, error)
        return redirect('/add')
    else:
        Item.objects.create_item(request.POST, request.session['id'])
        return redirect('/dashboard')

def show(request, id):
    if 'id' not in request.session:
        return redirect('/')

    context = {
        'items': Item.objects.filter(id=id)
    }
    return render(request, 'wishlist/show_item.html', context)

def delete(request, id):
    Item.objects.get(id=id).delete()
    return redirect('/dashboard')

def remove(request, id):
    Item.objects.delete(id, request.session['id'])
    return redirect('/dashboard')

def join(request, id):
    Item.objects.join(id, request.session['id'])
    return redirect('/dashboard')

apps/wishlist/templates/wishlist/create_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'wishlist/css/style.css' %}">
    <title>Create Item</title>
</head>
<body>
    <div class="container">
        <a href="/dashboard" class="nav">Home</a><br>
        <a href="/logout" class="nav">Logout</a>
        <h2>Create a new Wish List Item</h2>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <div class="form-container">
            <form action="{% url 'wishlist:createitem' %}" method="post">
                {% csrf_token %}
                <label for="name">Item/Product:</label>
                <input type="text" name="name"><br>
                <input type="submit" value="Add">
            </form>
        </div>
    </div>
</body>
</html>

apps/wishlist/templates/wishlist/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'wishlist/css/style.css' %}">
    <title>My Wish List</title>
</head>
<body>
    <div class="container">
        <a href="/logout" class="nav">Logout</a>
        <h2>Hello, {{ user.name }}!</h2>
        <h5>Your Wishlist</h5>
        <table>
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Added By</th>
                    <th>Date Added</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for item in myitems %}
                <tr>
                    <td><a href="{% url 'wishlist:show' item.id %}">{{item.name}}</a></td>
                    <td>{{item.user.name}}</td>
                    <td>{{item.created_at}}</td>
                    <td><a href="{% url 'wishlist:delete' item.id %}">Delete</a></td>
                </tr>
                {% endfor %}
                {% for item in added %}
                <tr>
                    <td><a href="{% url 'wishlist:show' item.id %}">{{item.name}}</a></td>
                    <td>{{item.user.name}}</td>
                    <td>{{item.created_at}}</td>
                    <td><a href="{% url 'wishlist:remove' item.id %}">Remove from my Wishlist</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h5>Other Users' Wish List</h5>
        <table>
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Added By</th>
                    <th>Date Added</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for item in allitems %}
                <tr>
                    <td><a href="{% url 'wishlist:show' item.id %}">{{item.name}}</a></td>
                    <td>{{item.user.name}}</td>
                    <td>{{item.created_at}}</td>
                    <td><a href="{% url 'wishlist:join' item.id %}">Add to my Wishlist</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'wishlist:additem' %}" class="additem">Add Item</a>
    </div>
</body>
</html>

apps/wishlist/templates/wishlist/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'wishlist/css/style.css' %}">
    <title>Login/Registration</title>
</head>
<body>
    <div class="container">
        <h2>Welcome!</h2>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <div class="row">
            <div class="one-half column">
                <div class="form-container index">
                    <h3>Register</h3>
                    <form action="/register" method="post">
                        {% csrf_token %}
                        <label for="name">Name:</label>
                        <input type="text" name="name" class="u-full-width">
                        <label for="username">Username:</label>
                        <input type="text" name="username" class="u-full-width">
                        <label for="password">Password:</label>
                        <input type="password" name="password" class="u-full-width">
                        <label for="confirm_pw">Confirm PW:</label>
                        <input type="password" name="confirm_pw" class="u-full-width">
                        <label for="date_hired">Date Hired:</label>
                        <input type="date" name="date_hired"><br><br>
                        <input type="submit" value="Register">
                    </form>
                </div>
            </div>
            <div class="one-half column">
                <div class="form-container index">
                    <h3>Login</h3>
                    <form action="/login" method="post">
                        {% csrf_token %}
                        <label for="username">Username:</label>
                        <input type="text" name="username" class="u-full-width">
                        <label for="password">Password:</label>
                        <input type="password" name="password" class="u-full-width"><br><br>
                        <input type="submit" value="Login">
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

apps/wishlist/templates/wishlist/show_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'wishlist/css/style.css' %}">
    <title>Show Item</title>
</head>
<body>
    <div class="container">
        <a href="/dashboard" class="nav">Home</a><br>
        <a href="/logout" class="nav">Logout</a>
        {% for item in items %}
        <h2>{{item.name}}</h2>
        <h5>Users who added this product/item under their wish list:</h5>
        <ul>
            <li>{{item.user.name}}</li>
            {% for user in item.join.all %}
            <li>{{user.name}}</li>
            {% endfor %}
        </ul>
        {% endfor %}
    </div>
</body>
</html>